Declaring a few examples as valid.
I've only checked against the BNF for 'text'*1323, but I'd expect it's
about the same for the other cases.

<value_expression>
-> <numeric_value_expression>
-> <term>
-> <term> <asterisk> <factor>
-> <numeric_primary> * <factor>
-> <value_expression_primary> * <value_expression_primary>
-> <unsigned_value_specification> * <unsigned_value_specification>
-> <general_literal> * <unsigned_numeric_literal>
-> <character_string_literal> * <exact_numeric_literal>

Incidentally, I think the reason is that SQL does auto-casting (again, I've
not checked the standard text).  cf.

gavo=# select 'text'*12;
ERROR:  invalid input syntax for integer: "text"
LINE 1: select 'text'*12;
               ^
gavo=# select '13'*12;
 column
----------
      156
(1 row)